env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
rules: {
   "indent": [0],
   "linebreak-style": [0],
   "max-len": [0],
   "no-else-return": [0],
   "consistent-return": [0],
   "prefer-promise-reject-errors": [0],
   "no-use-before-define": [0],
   "no-async-promise-executor": [0],
}
